---
- name: Ensure curl is installed.
  win_chocolatey:
     name: curl
     state: present
     
- name: Ensure Java is installed
  win_chocolatey:
     name: jdk8
     state: present
     
- name: Ensure Jenkins is installed.
  win_chocolatey:
     name: jenkins
     state: present
  register: jenkins_install_package_win
