---
# Jenkins doesn't allow updates via CLI, though that is required before plugins
# can be installed via CLI. See: https://gist.github.com/rowan-m/1026918
- name: Create Jenkins updates folder.
  win_file:
    path: "{{ jenkins_home }}/updates"
    state: directory
  register: jenkins_plugins_folder_create

# - name: Update Jenkins plugin data.
#   raw: >
#     curl -L https://updates.jenkins-ci.org/update-center.json | Select -Skip 1 | Select -SkipLast 1 > "{{ jenkins_home }}/updates/default.json"
#     creates="{{ jenkins_home }}/updates/default.json"
# 
# - name: Permissions for default.json updates info.
#   file:
#     path: "{{ jenkins_home }}/updates/default.json"
#     owner: jenkins
#     group: jenkins
#     mode: 0755
#   when: jenkins_plugins_folder_create.changed
# 
# - stat: path={{ jenkins_admin_password_file }}
#   register: adminpasswordfile

- name: Install Jenkins plugins using password.
  raw: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
    install-plugin {{ item }}
    --username {{ jenkins_admin_username }}
    --password {{ jenkins_admin_password }}
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_admin_password != ""
  notify: restart jenkins